configfile : "config.yaml"

## TODO INSERT HERE A CONTROL OF THE CONFIG FILE





## DEMULTIPLEXING IF NEEDED (and first filter on cells)
rule checkConfigFile:
    input: "config.yaml"
    output:
        "out.txt"
    shell:
        "Rscript rules/hello.r {config[PATH_TO_ALIGNED_FILE]} > {output}"

if config["MULTIPLEXING"] :
    print("Starting DEMULTIPLEXING")
