OUTPUT_DIRECTORY: outputs/

SAMPLES_INFORMATIONS_PATH: "/Users/asilvert/Programmation/Doridot/doridot-sncell/samples_info.tsv"

## QUALITY CONTROL ##
MIN_RNA_PER_DROPLET: 2000
MAX_RNA_PER_DROPLET: 30000
MIN_FEATURES_PER_DROPLET: 500
MAX_FEATURES_PER_DROPLET: 10000
MAX_PERCENT_MT_READS: 10
SPECIE: "Mouse" #Human or Mouse, Used to detect mithochondrial DNA

## MULTIPLEXING STEP ##

MULTIPLEXING: True #Must be True if you're using multiplexing, False otherwise
