PATH_TO_ALIGNED_FILE: "/shared/projects/placentatlas/CellRangerHashtagSnRNAseqCBA/"

OUTPUT_DIRECTORY: outputs/
OUTPUT_PREFIX: superexperiment

SAMPLE_INFORMATIONS_CSV_FILEPATH : ???

## MULTIPLEXING STEP ##

MULTIPLEXING: True #Must be True if you're using multiplexing, False otherwise

EMPTY_DROPLETS_EARLY_FILTERS:
  - 200 # Corresponds to TODO
  - 20 # Corresponds to TODO
